### ISSUE TITLE
Weird "_ideal" values calculated by mt_deviations()

### ISSUE THREAD

**Issue by mstbr** [PascalKieslich/mousetrap#11]
Hi Pascal,

I noticed that there can be trajectories for which mt_deviations() comes up with values for both xpos_ideal and ypos_ideal that seem off. Please consider the 10-point trajectory in the example below. For example, the values for ypos_ideal start at 0 and decrease for a number of steps before increasing towards 1. They should be monotonically rising, though.

I hope this isn't just based on a fault of mine.

Best,
Mathias

```
library(mousetrap)

xpos <- c(-0.3, 0.121649484536082, 0.342201834862385, 0.446153846153846, 
0.466942148760331, 0.414876033057851, 0.284615384615385, 0.0532110091743122, 
-0.332989690721649, -1)

ypos <- c(0, 0.241237113402062, 0.396330275229358, 0.507692307692308, 
0.59504132231405, 0.669421487603306, 0.738461538461539, 0.809174311926605, 
0.890721649484536, 1)

mt_x <- mt_add_trajectory(mt_example, xpos = xpos, ypos = ypos, id = "deviations")
mt_x <- mt_deviations(mt_x)
mt_x$trajectories["deviations",1:10,2:5]
```

**Comment by PascalKieslich** [comment]
Hi Mathias,

thanks for raising the issue and providing the example code.

I actually think that everything is fine with the idealized positions although they can be confusing. 

Based on your example code I created a simple plot (red points are the actual trajectory points, blue are idealized trajectory points):
```
png("ideal_traj_example.png",units="px",width=600,height=645)

plot(mt_x$trajectories["deviations",,c("xpos","ypos")],xlim=c(-1,0.5),ylim=c(-0.5,1),type="l")
points(mt_x$trajectories["deviations",,c("xpos","ypos")],col="red")
points(mt_x$trajectories["deviations",,c("xpos_ideal","ypos_ideal")],col="blue")

dev.off()

```

![ideal_traj_example](https://user-images.githubusercontent.com/13104756/64339867-2ebb5480-cfe5-11e9-804d-df8524115f29.png)

If we look at the plot, everything seems to be in order. However the development of the ideal positions still is a bit confusing, for example the initial decrease and then increase of the y positions of the idealized trajectory that you mentioned. This happens because at the start position the trajectory position matches the position on the idealized trajectory (the straight line connecting the start and end point). As the trajectory moves away from the straight line, the idealized position is determined by dropping a perpendicular from the observed position to the straight line. Since the movement away from the straight line is in the beginning larger along the horizontal compared to the vertical dimension this results in an idealized position that is placed below the start point of the trajectory. This changes as the trajectory moves upwards.

Hope this helps!

Best,

Pascal

**Comment by mstbr** [comment]
Oh man, that one took a while to understand. Sorry for being dense, your patient explanation is spot on.

Thanks a lot!

**Comment by PascalKieslich** [comment]
No worries at all!
