### ISSUE TITLE
mt_diffmap error "Determine joint bounds  Error in x[, , dimensions[1]] : incorrect number of dimensions" and "Error in x[[use]][!condition, , ]: (subscript) logical subscript too long"

### ISSUE THREAD

**Issue by gjoue** [PascalKieslich/mousetrap#13]
Hi,

I used your toy example in this message
# https://github.com/PascalKieslich/mousetrap/issues/12

and added a grouping variable

`grp = c('G1','G1','G1','G2','G2','G2')`
`dummy = data.frame(grp, x, y, unix_time, event_time, sequence_number)`

When I run the following to create a difference heat map:

`mt_diffmap(test, condition = "grp", 
           filename = NULL)`

it throws the error:

 `Determine joint bounds 
Error in x[, , dimensions[1]] : incorrect number of dimensions`

because `x` is a 2D matrix

The complete line of code is

`debug: range_x1 = range(x[, , dimensions[1]], na.rm = TRUE)`

By the way, if I call `mt_import_long` without specifying `timestamps_label` (because my real data is on msec resolution and doing an `as.numeric` on my POSIXct timestamps results in sampling points with the same timestamp so I thought I'd let `mt_import_long` create the timestamps) results in this error when I call `mt_diffmap`:

`Error in x[[use]][!condition, , ] : 
  (subscript) logical subscript too long`

I'd appreciate any help -- thanks!
Gina

**Comment by PascalKieslich** [comment]
Hi Gina,

thank you for bringing up these questions.


**Regarding the first question:**

I think the reason why mt_diffmap does not work in your example is because in this example each condition (i.e., G1 and G2) contains only a single trajectory. I replicated this behavior with the `mt_example` object provided in mousetrap:

`mt_diffmap(mt_subset(mt_example,mt_id%in%c("id01","id05")), condition = "Condition", filename = NULL)`
does not work and returns the same error message you described above.

`mt_diffmap(mt_subset(mt_example,mt_id%in%c("id01","id02","id05")), condition = "Condition", filename = NULL)`
does work as now each condition contains two trajectories.

Although this is in theory an issue, I think it is not an issue in practice because you would like to use mt_diffmap only in the case when you have multiple trajectories per condition, as only then it makes sense to compare the heatmaps between conditions.


**Regarding your second question:**

Here I have to speculate a bit, but I think the following is happening: If you do not want to import the timestamps into mousetrap, simply leaving out the timestamps_label argument in mt_import_long is not enough, because then the timestamps of the raw data get added to the data part of the mousetrap object, which results in several rows per trajectory. If this is true, you should actually already get the following warning message from mt_import_long:
"After removing trajectory data, more than one unique row per mt_id remains."

If this is happening, all following functions that use variables from the data object to group trajectories (like mt_diffmap) won't work properly because there now are multiple lines per trajectory in data.

A simple fix for this is to simply exclude the timestamps variable from the raw data before calling mt_import_long. Or to actually import the data with timestamps but ensure that the conversion into numeric does not results in duplicate timestamps.


Hope this helps! Please let me know if you have additional questions!

Best,

Pascal

**Comment by gjoue** [comment]
Thanks a lot for the detailed reply, Pascal!

For my first question, I actually had the same error message with my real data (so a lot more trajectories per group). I think I've finally figured out that the problem was the input data I fed to `mt_import_long` which contained a lot more columns that necessary for `mousetrap` -- once I only passed through only the columns needed for the import plus whatever grouping variables I wanted to use for later `mousetrap` functions AND fix my microsecond-resolution time stamps, I finally get much farther than before without getting any errors (but I still have a problem with `mt_diffmap` for which I'll open another thread because the symptoms are different, but maybe not...

For others who might come up against the problem of losing microsecond resolution and hence getting several timestamps that are "the same", specifying `options(digits=15)` before using `as.numeric` on my microsecond time stamps was what did the trick.
Thanks again.
