### ISSUE TITLE
mousetrap-measures computed on irregular and on equidistant versions of the trajectories

### ISSUE THREAD

**Issue by sbrockhaus** [PascalKieslich/mousetrap#8]
As a sensitivity analysis I computed the mouse-measures once on the original irregular data and once on an equidistant version of the trajectories. 
For some measures, there is some difference, e.g. for idle_time, hovers; 
for the velocity and acceleration measures it makes quite a big difference. 

Consider the following MWE:

```
library(mousetrap)

mt_data <- mt_example

## make the timestamps irregular 
mt_data$trajectories[  , , "timestamps"] <- mt_data$trajectories[  , , "timestamps"] + runif(38*465, 0, 9)

#### compute equidistant versions of the trajectories with timestamps every 50 milliseconds
mt_data <- mt_resample(mt_data, exact_last_timestamp = FALSE, 
                       save_as = "rs_trajectories",
                       step_size = 50L) ## method = "constant" 

## compare regular and irregular version of trajectories
plot(mt_data$trajectories[1, , "timestamps"], mt_data$trajectories[1, , "ypos"])
points(mt_data$rs_trajectories[1, , "timestamps"], mt_data$rs_trajectories[1, , "ypos"], col=2, type="b")


## compute mousetrap measures using the equidistant version of the trajectories
mt_data <- mt_derivatives(mt_data, use = "rs_trajectories") 
mt_data <- mt_measures(mt_data, flip_threshold = 0, use = "rs_trajectories", 
                       save_as = "measures", hover_threshold = 200)


## compute the mouse-measures on irregular observations 
mt_data <- mt_derivatives(mt_data, use = "trajectories") 
mt_data <- mt_measures(mt_data, flip_threshold = 0, use = "trajectories", 
                       save_as = "irregular_measures", hover_threshold = 200)

## plot the measures computed on regular and irregular observations 
for(i in 2:ncol(mt_data$irregular_measures)){
  plot(mt_data$measures[,i], mt_data$irregular_measures[,i], 
       main = colnames(mt_data$measures)[i], xlab = "computed on equidistant trajectories", 
       ylab = "computed on irregular trajectories")
}

all(colnames(mt_data$measures) == colnames(mt_data$irregular_measures))
```
 
Do you have a recommendation whether irregular or regular time-stamps should by used?

**Comment by PascalKieslich** [comment]
Thanks for bringing up this topic!



The divergence for some of the measures can be explained by several aspects of your simulation:

1) The value for `step_size` used in `mt_resample` is quite large (50). You should set it to some smaller value, ideally one that is comparable to or even smaller than the average timestamp difference for the original irregular timestamps (e.g., 5 or 10).

2) The first timestamp should be 0 - otherwise `mt_resample` will add a period without mouse movement starting at timestamp 0. You could reset the timestamps directly after adding the random noise with the following code:
`mt_data$trajectories[,,"timestamps"] <- mt_data$trajectories[,,"timestamps"] - mt_data$trajectories[,1,"timestamps"]`

3) The random function you are using can lead to negative timestamp differences, as in very few cases the original timestamps had a difference < 10. However, this only occurs for very few cases, so it should not be major issue, but it can especially mess up the calculation of min / max velocity and acceleration values.



I have reset the timestamps to 0 and used  `mt_resample` with `step_size=5` . Then, I computed the correlation of all measures using:
`sort(diag(cor(mt_data$measures[,-1],mt_data$irregular_measures[,-1])))`

The correlation of all measures (except some acceleration and velocity measures) is >.999, meaning that you should be able to compute those measures even with irregular timestamps (although it might make sense to use `mt_resample` to be on the save side).

Differences for the acceleration and velocity measures can be explained by my third point and by the fact that the value for velocity and acceleration depends on the timestamp differences - if these vary, very strange results might occur. For these measures, I would argue strongly in favor of using `mt_resample` beforehand.

**Comment by sbrockhaus** [comment]
Thanks a lot for clarifying!
